### ISSUE TITLE
Some x-axis symbols don't appear correctly when viewed in Excel

### ISSUE THREAD

**Issue by dplatten** [highslide-software/export-csv#46]
This is the same issue as listed here: https://github.com/highslide-software/export-csv/issues/27

I have some greater-than-or-equal-to symbols on the x-axis of a plot. These don't appear correctly in the csv or xls file. It can be fixed by changing line 195 to:

'data:text/csv;charset=utf-8,%EF%BB%BF' + csv.replace(/\n/g, '%0A'),

Regard,

David

**Comment by highslide-software** [comment]
Fixed by 15d35fbf9eace106da95e70e3b065ab901a56ea8
