### ISSUE TITLE
Data replacement causes errors in export

### ISSUE THREAD

**Issue by afager** [highslide-software/export-csv#48]
I have an application where I need to reset the data in the chart, I have 1 series that is rendered and an unknown number of dynamically generated series, which I export. When I replace the data (by removing the old sets and adding the new sets), the export generates this error:

Uncaught TypeError: Array.prototype.forEach called on null or undefined
S.HighchartsAdapter.S.HighchartsAdapter.a.init.each.Array.forEach.g @ highstock.js:23
(anonymous function) @ export-csv.js:38
S.HighchartsAdapter.S.HighchartsAdapter.a.init.each.Array.forEach.g @ highstock.js:23
Highcharts.Chart.getDataRows @ export-csv.js:35
Highcharts.Chart.getCSV @ export-csv.js:85
H.Chart.exportChartLocal @ highcharts-export-clientside.js:241
handlerBuilder @ highcharts-export-clientside.js:115p.contextMenu.a.separator.l.onclick @ exporting.js:18

I've checked that all the series have data, and that they are populating correctly and that is the case. After that I'm not exactly sure what the best way to fix/circumvent this issue is.

Thanks!

**Comment by highslide-software** [comment]
Can you show us a live demo? In this case it works as expected: http://jsfiddle.net/highcharts/cqjvD/799/

**Comment by afager** [comment]
https://jsfiddle.net/cqjvD/801/

that shows the issue. adding a new series after deleting old ones seems to cause the issue. I traced in the the export-csv.js file and it appears that the chart.series.points is not updated after a remove().

**Comment by highslide-software** [comment]
In you're demo, you're calling `addSeries` with an invalid argument. It is supposed to be a series config, while you are only passing the data itself. When done correctly, the getCSV method also works: http://jsfiddle.net/highcharts/cqjvD/808/

**Comment by afager** [comment]
Hi I took yours and found the same bug exists, you can't use the getCSV function if any series is set to visible:false.
https://jsfiddle.net/tt41v3sj/1/

**Comment by afager** [comment]
bump
