### ISSUE TITLE
Wrong scatter export - 2 points with the same date 

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/export-csv#49]
Example: http://jsfiddle.net/cqjvD/789/

**Comment by personman** [comment]
It's possible that #66 fixes this.

**Comment by mahtikebab** [comment]
Does the tooltip support this fix also? I have a basic line chart with one datetime on xaxis that has 2 y values. They show up correctly but using a shared tooltip I only get one of the points to show up in the tooltip.formatter -method's 'this.points'-array, making the tooltip show only 1 value of the series.

**Comment by highslide-software** [comment]
@mahtikebab The tooltip hasn't got anything to do with the export-csv module. 

Instead of a line chart, you probably want a scatter chart with a `lineWidth` setting. Then the tooltip will be able to handle unsorted data.
