### ISSUE TITLE
Regression: Not exporting all series in the chart data

### ISSUE THREAD

**Issue by tomascassidy** [highslide-software/export-csv#57]
v1.3.4 from the gh-pages branch no longer exports all series in the csv or xls file.  This problem was not present in v1.3.3.  I believe the regression was introduced in commit 3c675a4dfcfce494e1615e338e9efad135a21539.

Example: http://jsfiddle.net/cqjvD/836/

When running the example, the series labels from all chart series are exported but only the data for the first and last series is exported.

**Comment by tomascassidy** [comment]
I have also verified the problem exists on master branch.

**Comment by revjackstains** [comment]
I have verified the problem exists for several data sets.

Only the xAxis and the first two series are saved as CSV.

This example shows the error:

var chart = new Highcharts.Chart({

    chart: {
        renderTo: 'container'
    },

    title: {
        text: 'Categorized chart'
    },
    
    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },

    series: [{
        data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    },
            {
        data: [39.9, 61.5, 96.4, 99.2, 111.0, 156.0, 125.6, 128.5, 116.4, 164.1, 75.6, 34.4]
            },
            {
        data: [9.9, 41.5, 76.4, 49.2, 101.0, 136.0, 85.6, 28.5, 16.4, 64.1, 7.6, 4.4]
            }]

});

$('#getcsv').click(function () {
    alert(chart.getCSV());
});

**Comment by highslide-software** [comment]
Fixed, thanks!

**Comment by revjackstains** [comment]
Thanks, I can confirm it is now working as expected for me :-)
